### ISSUE TITLE
Save password and add post-init scripts

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#126]

**Comment by franchesko1437** [comment]
Levak? ignore?

**Comment by Levak** [comment]
1. Edit wb_launcher.hta to your needs. Saving password is not supported due to security concerns of such implementation.
2. When bot is ready and logged in, just type exec file with file a text file containing commands you can type directly in the console. Post-init scripts are on the todo list, but after a first implementation attempt I faced some design issues in the current command workflow that needs to be taken care of first. No ETA.
