### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by BrenoDh** [Levak/warfacebot#141]
is it possible to integrate with web server?

**Comment by nathan130200** [comment]
@BrenoDh you need to implement byself an api. I Recommended using C WebSocket Server and HTML 5 WebSockets to stream data.

**Comment by nathan130200** [comment]
@BrenoDh or use an rest Framework like in NodeJS: Node Express With Body-Parser
For node express install these packages:
`npm i express body-parser lodash`

```js
var express = require('express');
var bodyparser = require('body-parser');
var app = express();

app.use(express.static(__dirname+'/www')); //this able to use www folder as .html files
app.use(bodyparser.json());

app.post('/api/some_path_here_like_account_or_gameroom_open', function(request, response){
  // do something with request and response data. and integrate with your express static (HTML)
});```

**Comment by Levak** [comment]
Or try to use the already implemented DBus proof-of-concept (requires GNU/Linux and a stack that supports DBus, like Python/Flask):
https://github.com/Levak/warfacebot/issues/59#issuecomment-285880745

The DBus API has never been polished and always stayed as an undocumented POC because it requires heavy rework to support feedback from the command module.

**Note:** if you implement yourself an API for warfacebot, keep in mind that modifying warfacebot (even hid behind a webserver to your users) requires redistribution of the modified source code to the said users, as warfacebot is licensed under APGLv3.

**Comment by BrenoDh** [comment]
How do I implement an api that I can use in php?

**Comment by nathan130200** [comment]
@BrenoDh use Laravel (PHP Framework) and modify WarfaceBot to send data to your php rest api.
