### ISSUE TITLE
Update Warface_Ru 2017.10.02

### ISSUE THREAD

**Issue by 1bot1** [Levak/warfacebot#144]
Hello. I'm new. The game's clique has been updated and now the bots do not start. The latest files have been downloaded, but the result is the same.
P.S. I apologize if there is something wrong.

**Comment by Viktor20217** [comment]
Нам нужно создать программу, которая обновит бота :D

**Comment by Levak** [comment]
This hotpatch fixes 3 security flaws I've reported to Crytek 2 years ago:
 - Weak encryption key;
 - Common encryption key across all users;
 - Bruteforceable key.

Basically this update made a proper use of the mcrypt encryption by using integer array instead of byte array.

I'll be pushing the new RU key once the latter finishes cooking.

**Note**: It will require an update of the warfacebot binary (recompilation, or release download) to 1.0.11, which I will also push tonight.

**Comment by Levak** [comment]
Released
https://github.com/Levak/warfacebot/releases/tag/1.0.11

**Comment by Levak** [comment]
Nevermind, blocking bug on Windows, getline limited to 255 characters, the key is 360 bytes long, truncated, fails to connect.
Works fine on GNU/Linux tho.

**Comment by 1bot1** [comment]
Unfortunately does not work.
The command window appears, but does not connect to the game.
P.S. maybe someone from the Russian will finish under our gaming client, discard the link if it works.

**Comment by Levak** [comment]
> P.S. maybe someone from the Russian will finish under our gaming client, discard the link if it works.

What do you mean? banning? or fork?

**Comment by Levak** [comment]
Also works with Cygwin, so this is only a problem with Mingw and/or Windows

**Comment by 1bot1** [comment]
Maybe you're right. On Windows it does not work for me. There is no other OS. Can not fix this, what would it work in Windows?

**Comment by Levak** [comment]
Fixed in 3a085fa3f2e1554378bd0efd42fc57c17700969f

Re-Released
https://github.com/Levak/warfacebot/releases/tag/1.0.11

**Comment by 1bot1** [comment]
Thank you. This version works for Windows 64-bit.
P.S. Tell me please what game_hwid used to run a few bots.
