### ISSUE TITLE
Russian characters not displayed

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#155]
![159494](https://user-images.githubusercontent.com/29465298/31401888-f0f105a2-adfc-11e7-9512-c61860ba96a2.JPG)
Levak helps. Why, instead of Russian characters are displayed numbers? Look at the screenshot. How can I fix it?

**Comment by Levak** [comment]
If you are using the binary releases, see #66

**Comment by Levak** [comment]
Are you using `wb_launcher.hta` or `wb.sh`?

**Comment by franchesko1437** [comment]
wb_launcher.hta

**Comment by Levak** [comment]
Then do what is indicated in #66

**Comment by franchesko1437** [comment]
You did not understand. The Russian language is displayed, but you can not enter it on the
![1541 8](https://user-images.githubusercontent.com/29465298/31402488-c8211944-adfe-11e7-8e36-e9d75f43f25b.JPG)

**Comment by Levak** [comment]
Have you tried it nonetheless?

**Comment by franchesko1437** [comment]
Yes, I tried. See screenshot
![849](https://user-images.githubusercontent.com/29465298/31402919-2c0a0f5a-ae00-11e7-8e4d-9f564be8bc9d.JPG)

**Comment by Levak** [comment]
Can you type these characters in the console without warfacebot launched?
Can you type these characters without debug mode? `make clean wb`

I cannot find any material on Google about this issue linked with Cygwin or readline.
What I do know is that on GNU/Linux there is no problem when typing Cyrillic in the console.

So, from there, it will be your duty to find what's wrong and what can be done. I cannot help here (unless you find a solution and I will integrate it if possible).

**Comment by franchesko1437** [comment]
1.yes
2.NO. Characters. do not enter


https://goo.gl/oNG9qv

**Comment by Levak** [comment]
Ok. I've dug up a little more into the issue and confirm the problem about inputting Unicode into the command prompt.

The issue seems to be a shared problem among all command-line programs under Windows, using `cmd.exe`. e.g. `mintty.exe` is said to be exempt of any problem.

I've read around and found no actual fix. The frustrating part is that, indeed, one cannot type any non-ASCII character at all in the prompt, even if these are correctly displayed once in `chcp 65001` page.

So, I came up to a simple "idea". If you want to write any command that requires Unicode, open a new text file, put your commands in there, and then run `exec yourfile.txt`.

PS: By doing this I've identified a bug in the `exec` command that leads to a crash if a line is empty and wb compiled in non-debug mode. Will try to push a fix soon.

References:
 - https://github.com/JuliaLang/julia/issues/6795
 - https://bugs.python.org/issue1602
