### ISSUE TITLE
Help x Cygwin or binary upgrade

### ISSUE THREAD

**Issue by Perequal** [Levak/warfacebot#185]
Hi levak, after an upgrade of windows 10 64 bit, Cygwin Warfacebot does not work:

Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.

I tried all the possible solutions, rebase - 32 bit version - reinstallation, but nothing always the same error.
I tried the 1.0.11 binary version that works, but the "lms" pvp map is missing in Quickplay, even after adding the seanwlk edit.
Can you give me some help? thank you

**Comment by Levak** [comment]
Regarding the first error, it seems to be a problem with Windows / Cygwin, not with warfacebot itself.
e.g. from the discussion here https://github.com/mintty/wsltty/issues/6

Binary releases work and are immuable, editing sources is useless if you don't recompile the said binary. Only configuration files, like the ones in the `cfg/` and `wb.cfg` allow you do modify the behavior of warfacebot without recompilation.

Regarding the `lms` mode, it is rather useless as it is a single player mode, needing 16 players instead of the usual 4.

**Comment by Perequal** [comment]
Thanks for the answer Levak but I had already seen the discussion last week but it was not helpful.
The reason for my interest in lms modality was for the search and the opening of other rooms, not private, without players of the same Clan that suggest in TS your position. The quickpaly lms in the game is full of abusers.
So, would it be hard to recompile for the new mode?
Or some advice on where to put my hands, I have already spent several hours to comb through all the files :)

**Comment by Levak** [comment]
> The reason for my interest in lms modality was for the search and the opening of other rooms, not private

It will be hard to achieve at all, considering the way LMS works (locked room when playing). Definitely not stock in Warfacebot anyway.

> So, would it be hard to recompile for the new mode?
> Or some advice on where to put my hands, I have already spent several hours to comb through all the files :)

It requires patience to get into compiling C code.

**Comment by Levak** [comment]
No answer, closing.
