### ISSUE TITLE
the console works but the bot is not online

### ISSUE THREAD

**Issue by rasalgoel** [Levak/warfacebot#191]
hi levak, so when i start your program and log in my bot account it starts the cmd like usual. but when i go ingame with my real account i see that my bot account is not online. he also doenst accept invites (and i set accept invite to 1 in the settings) 
could you help me ?

**Comment by Levak** [comment]
Is the console stuck after the copyright notice?
If no other information for the bot is shown (e.g. no nickname, no friendlist, no XP etc), then you are likely to not be connected on the server at all due to a wrong encryption key.

Make sure this folder is up to date with yours.
https://github.com/Levak/warfacebot/tree/master/cfg/server

**Note**: Encryption keys for servers change regularly (every update, approx every month) without the need to recompile warfacebot. Hence, binary releases are not necessary when only this changes (otherwise it would result in a new release every week).

**Comment by rasalgoel** [comment]
ah yes i updated the server folder ! thanks for your reply
