### ISSUE TITLE
End of stream on RU

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#20]
When using bot with any of ru server, stream ends after bot receives all shop offers.

```
...
cry_price='34' crown_price='0' game_price_origin='0' cry_price_origin='34' crown_price_origin='0' key_item_name=''/><offer id='20168' expirationTime='0' durabilityPoints='0' repair_cost='sniper_helmet_10,3000,36000;' quantity='0' name='random_box_54' item_category_override='' offer_status='normal' supplier_id='1' discount='0' rank='0' game_price='0' cry_price='32' crown_price='0' game_price_origin='0' cry_price_origin='32' crown_price_origin='0' key_item_name=''/></shop_get_offers>
read: End of stream (5)
##--(191)-> <iq xmlns='jabber:client' to='k01.warface' from='xxx@warface/GameClient'  type='get' ><query xmlns='urn:cryonline:k01'><player_status prev_status='9' new_status='0' to=''/></query></iq>
Closed readstream
^C^CClosed ping
^C^C^C^C
```
If the implementation is not ready yet, I guess it is reasonable to note about it somewhere.

**Comment by Platex** [comment]
Yes, on RU server bot for some reason does not work.
We are waiting for the author's reaction

**Comment by Levak** [comment]
Thanks for the report,

I actually can't test myself because stuck on the `create_profile` query for another reason. I assumed the launcher was correct because I could stay connected during a whole night. Since the rest of the protocol is shared between all servers, I also thought I was good to go.

3 problems related to RU then:
 - Random `Incorrect userid/token` on `get_account_profiles`
 - `Game version mismatch` on `create_profile`
 - Stream ends after completion of `join_channel`

**Comment by Levak** [comment]
Ok, I have part of the puzzle figured out.

> * Random `Incorrect userid/token` on `get_account_profiles`

Cannot reproduce anymore, I think 2e1bf93b58e7a38aaf6bf6bf5f3a883d98237a2a got rid of it.

> * `Game version mismatch` on `create_profile`

Due to the mandatory Cyrillic nickname. By default an empty nickname is given and is auto-filled by the server with the Gface nickname. On mail.ru, the nickname needs to be given. No ETA for a fix on this one as there is a work around: Create the profile with the official game.

> * Stream ends after completion of `join_channel`

Actually, after 10 seconds, due to an automatic kick from server. HWID of 0 is recognized and treated as invalid by auto-kick. Use `-d game_hwid=xxxxx` with `xxxxx` your (or a random but static one) HWID.

New problems:
 * Cannot open rooms, also due to mandatory Cyrillic game room names;
 * Stream ends after 4 minutes.

For the 4min kick, I don't think it's due to the additional encryption layer because the game doesn't use it on the mail.ru version (neither the bot nor the RU game client use it ATM). Another possibility is the lack of some queries, like a join to the global chat missing.

Investigating.

**Comment by Levak** [comment]
> * Stream ends after 4 minutes.

The game sends a HTTP requests every 4 minutes to `wf.mrac.games.ru`.
This seems to be the AC heartbeat. Without these packets the stream is ended and on the next login we receive the following popup (translated):

> The protection system has found that customer files are corrupted or game client is blocked Internet access. To return to the game, go through the recovery process and the integrity of the client, verify that anti-virus and firewall does not block client (TCP port 80)

The content of these packets are "obfuscated" and weigh from 13KB (first packet) to 32B (every 4 min).

IMHO, support to mail.ru will be compromised. It is possible to reconnect every 4 minutes but I guess it makes it a lot more "detectable" and "banish-able".

**Comment by alexalok** [comment]
> This seems to be the AC heartbeat.
Indeed, MRAC stands for MailRuAntiCheat (yup, they got dam fantasy xD)

> Without these packets the stream is ended
Maybe try to record packets during gameplay and just send this "recording " whilist bot is working?

**Comment by Levak** [comment]
In conclusion:

 - warfacebot allows 4 minutes of connection on the RU version _if and only if_ a valid HWID different than 0 is provided with the `-d game_hwid=xxx` command line option, or with a default config file `wb.cfg` in which you need to add the line `game_hwid = xxxx` with `xxxx` a valid HWID.

 - No ETA for >4 minutes of connection on RU as it requires to bypass MRAC (mail.ru anti-cheat) heart-beat.

**Comment by SWITCH3ED** [comment]
Help me please сhange HWID I  do not understand

**Comment by Levak** [comment]
> Help me please сhange HWID I do not understand

Then don't use warfacebot on Russian server.
