### ISSUE TITLE
Bot not showing online

### ISSUE THREAD

**Issue by reven1979** [Levak/warfacebot#205]
I am able to run the program and sign in using the Windows GUI, however once the cmd window appears I just the #CMD line.  I manually added the bot to my main friends list and when my main is online and the bot program is logged into the bot does not show up online.  Also after running the "friends" cmd it shows 0 friends.  Not sure what is going on any help or links to a more indepth step by step would be helpful.

**Comment by Levak** [comment]
Make sure the `cfg/server/` folder is up to date with newest updates. Binary releases don't include updates for these, because it can easily be updated by a simple c/p from github.

I have yet to add an explicit error message for this, but it's a challenging one (to not receive any feedback because the message you sent was wrongly encrypted).

**Comment by reven1979** [comment]
Awesome, that did the trick.   Thanks for the quick response.
