### ISSUE TITLE
Closes instantly [TR Server]

### ISSUE THREAD

**Issue by sx90** [Levak/warfacebot#218]
Hi Levak,
I am trying to login "GFACE - Turkey" server through your WarfaceBot Launcher. When i press login it shows up a cmd screen for about 1 millisecond and it closes up instantly.  Please help, thanks.

**Comment by Levak** [comment]
Does it do the same on the other realms? e.g. mycom-EU?
The "1 millisecond" part doesn't talk to me, unless GFACE changed their logon method, and thus returns no valid token, leading warfacebot to display the "usage" help instead of launching properly.
But I checked on my side, and besides the fact I am region-blocked, I can login and get warfacebot to "launch" (just not connect on the server).

Can you check, perhaps, if you have an outdated Internet Explorer version? Try with something like IE11.

**Comment by sx90** [comment]
Hey levak its working perfect now. I just wanna ask is possible to make them stay ingame. I mean can i farm kd on them ?

**Comment by Levak** [comment]
>  I mean can i farm kd on them ?

No, you can't. warfacebot is an implementation of the lobby protocol used by Warface, not of the CryEngine one.
