### ISSUE TITLE
Update RU server

### ISSUE THREAD

**Issue by franchesko1437** [Levak/warfacebot#220]
Customer version 1.16800.1526.41200
Levak, please update g.k.c

**Comment by Levak** [comment]
I already pushed that update. Please make sure to check out the repository prior to opening a ticket.

**Comment by franchesko1437** [comment]
Thanks

**Comment by 1bot1** [comment]
Respected. You made an update for the PTS, and today an update is installed with the same version on the main servers. Update them, please.

**Comment by 1bot1** [comment]
Or do I understand that I can replace the key for these servers myself?

**Comment by Levak** [comment]
I am confused.

I am pretty sure that when I pushed the update yesterday at 20:00 CET, RU (not RU-PTS) didn't receive any update. I saw a RU-PTS small patch update, but it didn't change the game version, maybe I misread and it was main servers 🤦‍♂️ .

Anyway, yes, the keys are the same since they use the same exact game version, but I will update the repository nonetheless.

Sorry @franchesko1437 .

**Comment by 1bot1** [comment]
Thank you for efficiency.

**Comment by franchesko1437** [comment]
@Levak.
I used what I had. They are identical. 1Bot1 all messed up
In any case, everything is fine. Thank you Levak
