### ISSUE TITLE
TR 

### ISSUE THREAD

**Issue by furkanp34477** [Levak/warfacebot#227]
TR NOT WORKİNG

**Comment by Levak** [comment]
Hi,
What do you mean by "not working"?
The game version was not updated.
The launcher works for me, up to the point where I cannot connect because I do not live in Turkey.
But the bot (black) window is launched, and there.

**Comment by SYSSlendeR** [comment]
[bandicam 2018-03-07 18-12-01-535.zip](https://github.com/Levak/warfacebot/files/1793214/bandicam.2018-03-07.18-12-01-535.zip)

**Comment by Levak** [comment]
@furkanp34477 is it the same behavior you are getting from @SYSSlendeR 's video?

@SYSSlendeR AFAIR, you need an up to date IE version. Everything works fine for TR on my end, as stated in my previous post.

In order to see the error message, you can maybe try to add a `& pause` at the end of the command string in `wb_launcher.hta` line 59([1])

```
 WshShell.Run("cmd /c chcp 65001 & wb.exe -t " + token + " -i " + userid + " -f ./cfg/server/" + server + ".cfg " + options + " & pause");
```

[1]: https://github.com/Levak/warfacebot/blob/master/wb_launcher.hta#L59
