### ISSUE TITLE
Question: How to port to another language.

### ISSUE THREAD

**Issue by nathan130200** [Levak/warfacebot#243]
I'm trying to port to .NET Core (.NET Multiplatform Linux/MacOS/Windows) but i'm learning C++, and some things i don't know how to migrate like recv/send protocol in warface (i only know that have 12 bytes when client send stanzas).<br>

You can provide some info about this. (I remember your analysis "How i Hacked into warface ingame protocol" but i presume that is outdated? and some links that point this url is broke 😢, otherwise i only read 12bytes using a some test explorer in C# i used MemoryStream and BitConvert to get int bytes 😂)

**Comment by Levak** [comment]
1. Any port of warfacebot in any other language have to use the AGPLv3 license too, since you are adapting its code to another programming language, effectively modifying it.

2. The "How I hacked into warface ingame protocol" link is invalid since the first day of its release, use the mirror instead[1]. But it is indeed outdated in regard to the encryption layer.

3. You have the entire warfacebot source code available here on Github.

[1]: https://stackedit.io/viewer#!provider=gist&gistId=b9a1852a0a17e334f041&filename=wfre

**Comment by nathan130200** [comment]
both side have 12 bytes initial packet? http://prntscr.com/jdor8v

**Comment by nathan130200** [comment]
Thank you! I'm begin implementation in csharp https://github.com/nathan130200/WarfaceBot
