### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#25]
**Suggestion:** introducing lang-files to translate bot terminal/whisper output and (optionaly) input

**Selecting language:** language should be selected via cvar at launch. 

**What to translate:** IMHO, there is no need to make bot input multilanguage as warface client itself do not allow characters other than ASCII. So translations should be available only for bot output (such as his whisper-answers or terminal flow).

**Where to store translations:** I suppose it would be logical to store `.lang` files in `./cfg/lang`

**Format of translations:** I'm not familiar with C, but in PHP, for example, it is common practice to use an array for each translation.

**List of translation candidates:**
- `xmpp_message.c:`
  - `78`
  - `140`
  - `147`
  - `154`
  - `178`
  - `213`
  - `218`
  - `238`
- `cmd_missions.c:`
  - `80`
  - `99`
  - `108`
- `wb_cmd:`
  - `38`

**Comment by Levak** [comment]
Thanks for the suggestion! I'll add that to the wish list. No ETA for now.

> **What to translate**: IMHO, there is no need to make bot input multilanguage as warface client itself do not allow characters other than ASCII. So translations should be available only for bot output (such as his whisper-answers or terminal flow).

Warface supports full UTF-8. XMPP layer too.

> **Where to store translations**: I suppose it would be logical to store .lang files in ./cfg/lang

`cfg` is for storing config files ending with `.cfg`. Although, lang files may be implemented using the CVar system. No preference at the moment. There is also glib for supporting translations, but I prefer not depending on glib for now with respect to the standard use of warfacebot.

**Comment by alexalok** [comment]
> Warface supports full UTF-8. XMPP layer too.

Even though it supports UTF-8, I was talking about game client _not allowing_ the usage of "unusual" characters. As most of ppl use bot via in-game whispers, there is no need to translate "_input_" because it will pretty always be in english letters/numbers. Bot "_output_", on the other hand, should be translated, because, as you mentioned, in fact, game client supports UTF-8.

**Comment by Levak** [comment]
> As most of ppl use bot via in-game whispers, there is no need to translate "input" because it will pretty always be in english letters/numbers. 

If we consider the support for Cyrillic script (for instance the RU version), rooms and user creation need *"input"* that is in **Cyrillic only**. Such input also need to be configurable.

**Comment by alexalok** [comment]
Hm, interesting idea. Firstly i thought about some type of cvar trigger between latin/cyrillic mode, but I guess configuring it via lang cvar would be more logical.

**Comment by dolongnao** [comment]
LOL, Vietnamese language on Warface EU.
![screenshot1077](https://cloud.githubusercontent.com/assets/14193264/17509645/41edc0d4-5e45-11e6-8f0a-69664b218b6e.jpg)
![screenshot1078](https://cloud.githubusercontent.com/assets/14193264/17509646/41f5ac72-5e45-11e6-8d6e-faa33ea7058f.jpg)

**Comment by Levak** [comment]
> LOL, Vietnamese language on Warface NA

You'll be kind enough not to abuse the chat system, ok? ;)

**Comment by dolongnao** [comment]
OH. Not
I only send personal messages only.

I do not know what to use it on a global channel

**Comment by Levak** [comment]
> I only send personal messages only.

Ok, better as is.

> Maybe Warface supports full UTF-8

It does, else it wouldn't support RU or VN versions.

**Comment by psychoeric** [comment]
Salut est ce que tu pourrais m aider a installer tout ca via tiewer ?? j ai essaye et j arrive pas ca serais gentil a toi " Amis a DArk-is-Back ;-) "

**Comment by Levak** [comment]
I've pushed a WIP branch to support multi-language support.

https://github.com/Levak/warfacebot/compare/lang-patch

For now, what it does is:
 - Translates most of wb UI/messages
 - Translates whisper messages
 - Fixes one problem of #20 regarding to opening game rooms (assuming we have a `russian.cfg` file)

Current issues/TODO:
 - Does not translate easy/normal/etc (not yet)
 - Does not translate command arguments (which include easy/normal/etc) and that, I have no idea what to do if previous point is done (perhaps display both).
 - `g_language` can only be set in `wb.cfg` and cannot be changed in command line (because of option parser which uses `LANG()` too)
 - Add other language files (ATM there is only `english.cfg`)

I would appreciate feedback, ideas or translations regarding this "big" refactoring.
For instance, I've noticed that `LANG_FMT` should be only used when necessary, because it makes each individual language file responsible for the format string, handled by the compiled `sprintf` and its arguments.

**Comment by alexalok** [comment]
> g_language can only be set in wb.cfg and cannot be changed in command line (because of option parser which uses LANG() too)

I don't see a reasonable use-case for changing language on-the-fly. One might want to change it when moving to another server, but it requires bot restart itself.

> I have no idea what to do if previous point is done (perhaps display both).

Two translations may be used - one for output (latin or cyrillic) and one for input (always latin, because in case of russian language using cyrillic translation on eu server is not possible for whisper commands) and there may be two variants supported as an argument - a mentioned input translation and a fallback-value (i.e. input value of default language, which i guess will be English).

Moreover, as we know which realms do not support non-latin characters in chat, a special cvar could define the fact that we can use output translation as an argument (in other words, that realm has all-characters support), giving us 3 options that can be used as argument: output and input translations and a fallback value.

**Comment by Levak** [comment]
Merged branch lang-patch into master. Reference commit a8b345f0ee3415bd5863651bfbb4dc54f04c1b3e

The TODO list above still applies. We will see over time how it goes. I keep the issue open for feedback.

> EDIT: since bot doesn't care if cyrillic whispers are supported or not, i think a cvar is not needed - instead, bot can always support all 3 argument variants i mentioned.

Will have to think of that. The fallback value cannot be in english.cfg, because we want undefined lang entries to be marked with `@`. This also means that new commands will be useable only using the `@` alternative. I am not a big fan of bringing localization to the command line, because it makes the README file useless in regard to giving help (not the same commands).
