### ISSUE TITLE
Owners' whitelisting

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#27]
**Proposal:** add cvars to make bot process "whisper" commands and accept followings/invites only from specified players or clannames.
One nickname/clanname per cvar, multiple cvars and their mixes possible.

**Comment by Levak** [comment]
Thanks for the idea,

At the moment, CVar names are statically compiled in order to improve performances. This means that such feature can only be made using a single CVar. 

That being said, there are 2 possible outcomes for this feature:

 - A String CVar containing coma or space-separated items, parsed at runtime every time used;
 - A List CVar which would only parse the input on set.

CVar lists are not implemented ATM, but can be an interesting thing to have.

**Comment by alexalok** [comment]
`A String CVar containing coma or space-separated items, parsed at runtime every time used`

comma can be used in a nickname, AFAIK, so it's better to use spaces, though it would harm readability (IMHO)
