### ISSUE TITLE
Zero stats bot

### ISSUE THREAD

**Issue by wnull** [Levak/warfacebot#356]
Faced with the fact that sometimes (in very rare cases) when you run the bot on the server, its game statistics (game profile) is reset. That is, literally all values in the profile are zero. I am very interested to know the reason for this. This loophole uses MechCraft, changing the number of achievements absolutely any of his bot to the value of `228`. 

I assume there is some internal directory (`temp`) where the stats can be spoofed. Am I right? If so, is there any way to edit it yourself? And if not, just explain why in rare cases the values are zero?

**upd**: it looks like this: https://i.ibb.co/HdFpS91/image.jpg

**Comment by Levak** [comment]
Statistics of this popup (screenshot) are sent by the client. Which means it "can" be spoofed by a compromised client (bot, cheat).

In warfacebot, statistics are re-computed based on the information available in the online profile, which means, by design, it doesn't  sent wrong information. Perhaps on "rare condition" as you describe, before profile initialization happened, it may send wrong/corrupted information.

If you compile yourself warfacebot, it is located here:
https://github.com/Levak/warfacebot/blob/master/src/xmpp_wf/result/xmpp_iq_peer_player_info.c#L58


Statistics of this popup are randomly sent to the lobby server by the player requiring the information as part of an internal validation process. If you send wrong info, the info is then sent back to the server for checking. Probably there is an internal reporting system if the information is incorrect. The reason why it is done this way is apparently historical reason - lobby server could not handle profile query for N users, so they delegate the task to the players, with random checking.

**Comment by wnull** [comment]
@Levak, thank you for the full explanation, now I will deal with this in detail.
