### ISSUE TITLE
GUI launcher - Internal error - Captcha

### ISSUE THREAD

**Issue by vlad28x** [Levak/warfacebot#38]
When you start the program - "internal error"
![default](https://cloud.githubusercontent.com/assets/24373447/20881965/fb340218-bb08-11e6-8148-2dc933292dd6.PNG)

What to do?

**Comment by Levak** [comment]
Hi,

Do you use the latest launcher from a day or so?
https://github.com/Levak/warfacebot/commit/f370636aa74891a215418d525f2e3896c8417182

Releases 1.0.5 and 1.0.5b are known to not work since the 30th of December following to new security policy related to Captcha on login. A new release is in the pipe, but waiting for additional feedback to see if it has no negative impact.

In the future, the GUI launcher for Windows could feature the graphical Captcha since it's made out of Javascript, but it is not in the pipe for now. Any contribution is welcome though.

**Comment by Levak** [comment]
> In the future, the GUI launcher for Windows could feature the graphical Captcha since it's made out of Javascript, but it is not in the pipe for now. Any contribution is welcome though.

Following to a Hub update today, captcha is now required on every single login endpoint, even when the credentials are valid. I don't know if they will change it in the near future, but this is starting to be a necessity to add reCaptcha support into the launchers. Command-line launcher will perhaps be unusable, I guess.

**Comment by SyclopX** [comment]
cant you add the captcha for GUI launcher

**Comment by viktor1986** [comment]
если переписать лаунчер и скрипт!как на скринах
![screenshot_4](https://cloud.githubusercontent.com/assets/13694709/21483643/b34faa6a-cbd9-11e6-80a1-cd627bd00f64.png)

**Comment by Levak** [comment]
> cant you add the captcha for GUI launcher

After looking at how to integrate recaptcha2 into the GUI launcher I stepped upon a Cross-Site forgery wall. As far as I understand, one cannot use the same site-key for the captcha in another domain (here localhost instead of warface.com), which makes sense. It is neither possible to integrate warface.com in an `<iframe>`. The official launcher is a browser in a nutshell (nw) which browses warface.com in the correct domain. Here, HTA, is a webpage application, and the browser is Internet Explorer.

So, yeah, I don't think a captcha will be a thing in the GUI launcher.

> if launcher and rewrite the script, how on screen

I think this is what I'll end-up doing (that's what I was already doing for the command line launcher).

**Comment by alexalok** [comment]
`Here, HTA, is a webpage application, and the browser is Internet Explorer`
can't you load a webpage somewhere in background, just like the official launcher?

**Comment by Levak** [comment]
> can't you load a webpage somewhere in background, just like the official launcher?

As I said, the official launcher is a custom browser which does everything they want in regard to domain policy. An HTA is "just" a webpage with enhanced Windows API, the browser behind is an unmodified Internet Explorer. When IE loads the HTA, the domain is "localhost" which is different than the "warface.com" one. In the official launcher, the domain is "warface.com". One cannot access the data and elements from another domain, it's the hole purpose of Cross-site forgery protections, unless you modify the browser itself, which is `nw`.

**Comment by alexalok** [comment]
> When IE loads the HTA, the domain is "localhost" which is different than "warface.com". 

Okay, I understand now
