### ISSUE TITLE
launch Bot

### ISSUE THREAD

**Issue by Carlsberg34** [Levak/warfacebot#388]
Why it is impossible from one virtual machine using Levak bot, it is impossible to start more than one bot, the second is switched off at once.

**Comment by Levak** [comment]
Because you're using the same account perhaps?

**Comment by Carlsberg34** [comment]
No, I use two different accounts.

**Comment by Levak** [comment]
Under mailru?
Do they have the same HWID?

**Comment by Carlsberg34** [comment]
Yes. I run them from one virtual machine

**Comment by Levak** [comment]
I meant by HWID, did you change `game_hwid` in `wb.cfg` with a 9 digits value?

**Comment by Carlsberg34** [comment]
How to change hwid?

**Comment by Carlsberg34** [comment]
![bandicam 2019-12-18 01-30-44-288](https://user-images.githubusercontent.com/53007121/71039707-76e22b00-212d-11ea-9971-1847dc54d6c4.jpg)

**Comment by Carlsberg34** [comment]
I don't understand what needs to change?

**Comment by Carlsberg34** [comment]
![bandicam 2019-12-18 12-20-23-057](https://user-images.githubusercontent.com/53007121/71072986-349a0780-2188-11ea-851e-ccf7e695b139.jpg)
already changed hwid, and still one bot works the second is not. I use version 1.0.16

**Comment by Levak** [comment]
AFAIR, mailru has some extra check compared to mycom. I just can't remember what is missing there.

For sure, 2 sessions with the same IP and same HWID will lead the other one to DC. 

For sure the same account used on 2 session, same server (or not!), will DC the other one.

For sure no HWID will DC the bot after few seconds.

For sure MRAC will DC any client with no heartbeat (like bots) after 4min, decreasing to 2min, 1min, etc. Resets after 5min no connection.

The only change since 1.0.16 that may affect this, is that the HTA launcher uses the same session (cookies) to send login requests (in order to work with MyGames login).

Maybe try to launch 2 different instances of the HTA launcher if that's what you are using?

**Comment by Carlsberg34** [comment]
I will then one bot to run

**Comment by Levak** [comment]
> I will then one bot to run

I did not understand you. Is launching 2 separate instances of the HTA launcher fixing your issue?

**Comment by Carlsberg34** [comment]
I did, ran 2 HT launcher, and still one bot crashes, the other remains.

**Comment by wnull** [comment]
@Levak,

> For sure MRAC will disconnect any client with no heartbeat (like bots) after 4min, decreasing to 2min, 1min, etc. Resets after 5min no connection.

Hmm, is there a way around these restrictions? For example, the use of proxies?

**Comment by Levak** [comment]
> Hmm, is there a way around these restrictions?
> For example, the use of proxies?

Even if there was, it would allow any cheater to write an MRAC heartbeat emulator and cheat freely. So no, there are no public way that I know of doing this. And if there was, I would immediately report it to mycom like I did for the previous methods that I've found in the past 2 years.
