### ISSUE TITLE
i need help about close th cmd

### ISSUE THREAD

**Issue by Mohamed-Slimane** [Levak/warfacebot#419]
hi Levak
I know I have more questions for you and thank you
I found that the connection is lost after 40 seconds
I have made the .hta file execute the login command every 40 seconds
So a new window opens with a new connection every 40 seconds
The old window disconnect because of the new connection
My request is how do I make the old window close automatically when connection replaced ,because the command did not work . is there were cache files ?.
![Screenshot_5](https://user-images.githubusercontent.com/23380229/75626594-004fb800-5bc9-11ea-9863-4d77de9725b3.png)
![Screenshot_6](https://user-images.githubusercontent.com/23380229/75626597-047bd580-5bc9-11ea-9c84-f4e7abda2ac5.png)

this is th hta file
![Screenshot_7](https://user-images.githubusercontent.com/23380229/75626666-a56a9080-5bc9-11ea-86f9-9495fe33e01b.png)

**Comment by Levak** [comment]
> 40 sec

It goes worse and worse every time MRAC disconnects you within 5 min. So first time is 5min, then 4, then 2, then 1, then 30 sec etc.

> My request is how do I make the old window close automatically when connection replaced

It is supposed to close, but Windows is not really nice about it. Everything works fine on Linux and I don't really use bots on Windows since the MRAC of your PC that is used to play on your main account can detect the bot running in background. I believe if detected this way, MRAC issues an automatic 10 days ban on the main account. Use a VM, or another computer for bots, always.

> return 0;

You are missing `{` and `}` in the `if` scope. Then you need to recompile with `make` (you need a toolchain and a C compiler).

**Comment by Mohamed-Slimane** [comment]
Oh . 
i have 3 bots accounts and every bot have folder alone with Different hw_id.  
the bots is online fore 1 hour. 
am using windows server 2016  rdp for the bots

the problem only the windows opened
i have to close it manually every time

![Screenshot_8](https://user-images.githubusercontent.com/23380229/75626797-e8793380-5bca-11ea-9295-a71eaef44119.png)

**Comment by Mohamed-Slimane** [comment]
if i change the server to linux its good ?
for make bots stay long time .

**Comment by Levak** [comment]
> if i change the server to linux its good ?

It will behave the way it is supposed to behave. Auto-completion, UTF-8 and exits as soon as closed.

> for make bots stay long time .

No, it won't change that.
