### ISSUE TITLE
Qos limit reached

### ISSUE THREAD

**Issue by Carlsberg34** [Levak/warfacebot#440]
![Desktop_200417_1142](https://user-images.githubusercontent.com/53007121/79551068-d7fd1980-80a1-11ea-8d75-cbe9b383069e.jpg)
 Hello, this error appeared today.
Server Alpha

**Comment by Levak** [comment]
I confirm the issue on RU only (maybe RU-alpha, idk)
Didn't look what was wrong there. At least the error message is correct.
Under normal circonstances it means the Master server is overloaded. But I don't see any stat drop on RU, and it does that with every channel.

It happens when you try to join a pvp channel, right?
Try `switch pvp_pro_001_r1` (or any valid pvp channel)

I can't look at the issue right now.

**Comment by Carlsberg34** [comment]
What should I do?

**Comment by Levak** [comment]
Is the issue still happening? I have tried again just now and had no issue queuing in Quickplay FFA on RU-Alpha server.

It probably was a server overload at the time of the ticket.

**Comment by Carlsberg34** [comment]
Problem solved
