### ISSUE TITLE
Add "owner" cvar

### ISSUE THREAD

**Issue by alexalok** [Levak/warfacebot#57]
Add a possibility to specify nickname(s) of player(s) whom whispers with owner-only commands (like quickplay, randombox, etc) will be executed. If no nicknames specified, disable support of owner-only commands via whispers.

Partially linked with https://github.com/Levak/warfacebot/issues/27, which says about whitelisting regular whisper commands.

**Comment by Levak** [comment]
This probably won't happen, as whisper commands are meant to emulate a real "human" interface. Do you often ask your buddy to open random boxes? If you want to remote-control the bot, you should _not_ use whispers, as all whispers are subject to logging and investigations. There is a DBus API for such _control_ - even though it is far from complete.

That put aside, all I can think of is restricting all whisper commands to only the friend list / clan mates, because ATM, a bot can talk to another bot with no restriction.

**Comment by alexalok** [comment]
`Do you often ask your buddy to open random boxes?`

I do ask them to start a quickplay and invite me, for instance. That thing is owner-only for some reason.

**Comment by Levak** [comment]
For quickplay, just use the official preinvites interface and select the bot ? Why would you need to use bot as quickplay initiator? There is one for regular invites in case you exit the room, command which can actually be disabled by cvars.

But for quickplay I see no reasons, am I missing something? ATM the command is owner-only for the sake of implementation, like it dumps get_config for no particular reason. There are other "useless as of now" implem-related features pending to be pushed that would not necessary mean adding a whisper command.

**Comment by alexalok** [comment]
> Why would you need to use bot as quickplay initiator

To bypass matchmaking system. To smurf.
