### ISSUE TITLE
Support for Warface China?

### ISSUE THREAD

**Issue by BOROH** [Levak/warfacebot#81]
Can I release a bot for Warface China?  http://wf.yanseyule.com/Index/index.html

**Comment by Levak** [comment]
Hi,
First, I would like to make sure what you mean by "release":

 - create a pull request which includes config and bash/js launcher to this repository and keep maintaining it;
 - create a fork of this repository with sources and original license included;
 - provide a binary release with sources and original license.

If what you had in mind is not _entirely_ described by one of the above, then the answer is probably "no". You need to follow the terms of the AGPLv3 license.

If on the other hand, you meant the first point (pull request), yes!

**Comment by BOROH** [comment]
У меня плохой английский и видимо поэтому Вы не поняли. Я спросил--будете ли Вы делать  ботов для китайского Warface?

**Comment by Levak** [comment]
Using google translate (I only speak French and English) on your post I now see you are asking if _I_ will release a bot for Warface CN.

The answer is "not if I find interest in it", but I will of course accept pull requests for it. BR, VN and RU were done that way. ATM, TH and CN versions are pending, mostly because they are not "simple" launchers and seem to require some Facebook authentication, so I put that aside for the time being

**Comment by Levak** [comment]
Closed since PCN is down for more than 3 weeks now.
