### ISSUE TITLE
Вылет после 5 секунд.

### ISSUE THREAD

**Issue by Dagger28** [Levak/warfacebot#82]
Уважаемый Левак. Подскажите, после запуска твинка, спустя 5 секунд он просто вылетает из игры.

**Comment by Levak** [comment]
Hi, I do not speak Russian, so I will try to answer using Google translate:

> Dear Levak. Tell me, after the start of the twint, after 5 seconds, it just flies out of the game.

I assume you are talking about the auto-leaving feature of the bot. If you want to disable this behavior, use `wb_leave_on_start = 0` in the command line or in a config file (e.g. `wb.cfg`).

But I feel the background question is because you want the bot to actually join you _inside_ the game, which is not possible ( see question #77 ).

If you are talking about the fact the bot _disconnects_ from the server after 5 seconds, you need to set `game_hwid` accordingly (depending on the publisher).

**Comment by Dagger28** [comment]
Нет, я не хочу, чтобы он присоединялся, скорее, чтобы он не вылетал из самой игры.

**Comment by Yoburguy** [comment]
Вылет из игры - провален тест на "железо" (HWID) - таким образом реализуется бан по железу. Боты не передают таких данных (за их неимением), соответственно следует кик (вылет). Понять и простить ;)

DC means hwid check test  fail - one  of the ways to perform  ban. Bots have no hwid, so it cause disconnect. Just accept this nature :)
